date = input ("Enter the date : ")
name = input("Enter your Name : ")
course = input ("Enter the Course : ")
department = input ("Enter your Department : ")
address = input("Enter your Address: ")
mobile_no = int(input("Enter your Mobile Number : "))
father_name = input( "Enter your Father Name : ")
mother_name = input ("Enter your Mother Name : ")
Ann_In = int(input("Enter your Annaual Income : "))
cgpa = float (input ("Enter your CGPA : "))
domain = input("Enter your Domain : ")

print("------------------------------------------")
print("Date : ",date)
print("Name : ",name)
print("Course : ",course)
print("Department : ",department)
print("Address : ",address)
print("Mobile : ",mobile_no)
print("Father_Name : ",father_name)
print("Mother_Name : ",mother_name)
print("Annual_Income : ",Ann_In)
print("CGPA : ",cgpa)
print("Domain : ",domain)

